version: 2.1

executors:
  lein:
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/repo

jobs:
  test:
    executor: lein
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: tonal-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: tonal-{{ checksum "project.clj" }}
      - run: lein test

workflows:
  version: 2.1
  general_build:
    jobs:
      - test